### PR TITLE
feat: automatically stop if the given id is achieved

### PR DESCRIPTION
**Pull request by Ethkuil**
Usage: pass the id to function `nextURL` as an argument.

### CODE REVIEW

**Comment by Co1lin** [comment]
Thanks for your contribution!

Do you mean the user has to pass `end_id` for every invocation of `nextURL` in the whole script before they run the script?

**Comment by Co1lin** [comment]
And also, what will happen if we don't close the window? Will it continue to play the last video again and again? Sorry, I can't remember clearly about this. My point is why we need to close the window at last.

**Comment by Ethkuil** [comment]
> Thanks for your contribution!
> 
> Do you mean the user has to pass `end_id` for every invocation of `nextURL` in the whole script before they run the script?

Not like that. JavaScript's variable is `undefined` by default, and `undefined` will never equals to the current url, so that it won't stop and just work like the last version.

(But indeed a user who never learn about programming may not find this implementation user-friendly. But I don't care🤣)

**Comment by Ethkuil** [comment]
> And also, what will happen if we don't close the window? Will it continue to play the last video again and again? Sorry, I can't remember clearly about this. My point is why we need to close the window at last.

That's because I want a clear way to tell me that it's all done. Then my first idea is to just close the tab and I found it works well. Certainly there exist other approaches but I think this may be the **easiest way**. (And there is a `setInterval` in `mainFunc`, just closing the window is a good way to avoid dealing with it.)

**Comment by Co1lin** [comment]
I'm not very familiar with js lol. Thanks for your explanation! Just curious, is it better to do `window.alert()`? I mean, if there's some error, and it skips all pages to reach the end_id provided, then it will close the window without any notice, and you have to reopen the window to check. However, if the window is not closed, you can see that all videos are marked completed on the webpage, which is more user-friendly. For a clear message about reaching the end, I think sending a popup alert would also be great. What do you think?

**Comment by Ethkuil** [comment]
Certainly it's OK but a little troublesome. And if do so, other changes needed are to save the interval ID and remove it by `clearInterval` when all videos are complete. As following:

```js
let intervalID;
...
intervalID = setInterval(worker, 1000, video, span_items[process_span_index]);
...
if (video_id === String(end_id)) {
    clearInterval(intervalID);
    ...
}
```

PS. When a tab have switched into another URL, all the info for debugging have gone. Whether closing it or not only decides whether user can see the state of last video or not.
PS. I'm not familiar with JS either and even haven't learned it systematically. When I have to write some basic JS code, Google, MDN, AI(Copilot and ChatGPT) are my savior lol.

**Comment by Ethkuil** [comment]
Supplementary: I did an experiment and found that the video keeps playing after `window.alert()`.

**Comment by Co1lin** [comment]
I see. So you want to stop running worker periodically and also stop playing the video after completion, right?

**Comment by Ethkuil** [comment]
> I see. So you want to stop running worker periodically and also stop playing the video after completion, right?

No no no, I don't want to `stop playing the video after completion` and just want to state that `window.alert()` doesn't give more useful info compared with simply closing the window. But certainly the prompt when complete is more user-friendly.

And how the program should act depends on what you deem to be best.

**Pull request merged**
